"""Deterministic Markdown matrix generator for Kernux agent profiles.

Reads canonical YAML profiles, validates them, and emits a stable
matrix/AGENT_MATRIX.md. No timestamps, no network, no overall score.

Every factual cell visibly exposes claim status, so a change from verified to
vendor-reported changes the matrix bytes.

Modes:
  default              write matrix/AGENT_MATRIX.md
  --check              fail (exit 1) if committed matrix differs from regenerated
"""

from __future__ import annotations

import argparse
import datetime as _dt
import sys
from typing import Any

from tools import profile_io, validate_profiles
from tools.profile_io import REPO_ROOT, ProfileFile

MATRIX_PATH = REPO_ROOT / "matrix" / "AGENT_MATRIX.md"

COLUMNS: tuple[tuple[str, str], ...] = (
    ("name", "Agent"),
    ("tracks", "Track(s)"),
    ("open_source", "Source availability"),
    ("license", "License"),
    ("surfaces", "Surfaces"),
    ("local_model_support", "Local-model status"),
    ("mcp_support", "MCP status"),
    ("headless_or_ci", "Headless/CI status"),
    ("evidence_status", "Evidence status"),
    ("last_verified", "Last verified"),
)

GENERATED_NOTICE = (
    "<!-- This file is generated by `uv run python -m tools.generate_matrix`. "
    "Do not edit by hand; edit agent profiles under agents/ instead. -->\n"
)

LEGEND = """\
## Legend

Each factual cell is rendered as `value \u00b7 claim_status` (for example
`supported \u00b7 vendor-reported` or `MIT \u00b7 verified`). `unknown` renders plainly
as `unknown` (no claim-status suffix). Values past their freshness window are
suffixed `\u00b7 STALE`.

- **Source availability** \u2014 whether the agent's source code is openly available.
- **Surfaces** \u2014 where the agent runs: terminal (TUI), IDE, web, desktop, async, or headless-server.
- **Local-model / MCP / Headless/CI status** \u2014 `supported` / `partial` / `unsupported` / `unknown`.
- **claim_status**:
  - `verified` \u2014 established from a directly inspectable artifact (repository, LICENSE, release metadata) or independent execution.
  - `vendor-reported` \u2014 a direct claim from official documentation, vendor website, or marketing; not independently reproduced.
  - `unknown` \u2014 no acceptable direct source; absence of documentation is not a vendor claim.
- **Evidence status** (derived):
  - `verified` \u2014 all factual fields verified.
  - `vendor-reported-only` \u2014 all non-unknown fields vendor-reported, none verified.
  - `partial` \u2014 a mixture of verified, vendor-reported, and/or unknown.
  - `unknown` \u2014 no non-unknown factual values.
- **Last verified** (derived) \u2014 the maximum verification date among sourced non-unknown factual fields.

No overall "Kernux Score" is computed or shown. Kernux is complementary to
SWE-bench and other academic benchmarks; this matrix is **not** a benchmark.
"""


def _tri(value: Any) -> str:
    if value in (None, "unknown"):
        return "unknown"
    return str(value)


def _render_list(values: Any) -> str:
    if values in (None, "unknown"):
        return "unknown"
    if isinstance(values, list):
        if not values:
            return "unknown"
        return ", ".join(str(v) for v in values)
    return str(values)


def _stale_suffix(field_value: dict[str, Any], *, evaluation_date: _dt.date) -> str:
    if profile_io.field_is_stale(field_value, evaluation_date=evaluation_date):
        return " \u00b7 STALE"
    return ""


def _cell_with_claim(
    field_value: dict[str, Any], *, render_value: str, evaluation_date: _dt.date
) -> str:
    if profile_io.field_is_unknown(field_value):
        return "unknown"
    cs = field_value.get("claim_status", "unknown")
    stale = _stale_suffix(field_value, evaluation_date=evaluation_date)
    return f"{render_value} \u00b7 {cs}{stale}"


def _cell_for(profile: dict[str, Any], key: str, *, evaluation_date: _dt.date) -> str:
    if key == "name":
        return str(profile.get("name", "unknown"))
    if key == "tracks":
        tracks = profile.get("tracks", []) or []
        return ", ".join(tracks) if tracks else "unknown"
    if key == "last_verified":
        return profile_io.derive_last_verified(profile)
    if key == "evidence_status":
        return profile_io.derive_evidence_status(profile)
    if key == "open_source":
        block = (profile.get("openness", {}) or {}).get("open_source", {}) or {}
        return _cell_with_claim(
            block, render_value=_tri(block.get("value")), evaluation_date=evaluation_date
        )
    if key == "license":
        block = (profile.get("openness", {}) or {}).get("license", {}) or {}
        return _cell_with_claim(
            block,
            render_value=str(block.get("value", "unknown")),
            evaluation_date=evaluation_date,
        )
    if key == "surfaces":
        block = (profile.get("compatibility", {}) or {}).get("surfaces", {}) or {}
        return _cell_with_claim(
            block, render_value=_render_list(block.get("value")), evaluation_date=evaluation_date
        )
    if key == "local_model_support":
        block = (profile.get("compatibility", {}) or {}).get("local_model_support", {}) or {}
        return _cell_with_claim(
            block, render_value=_tri(block.get("value")), evaluation_date=evaluation_date
        )
    if key == "mcp_support":
        block = (profile.get("protocols", {}) or {}).get("mcp_support", {}) or {}
        return _cell_with_claim(
            block, render_value=_tri(block.get("value")), evaluation_date=evaluation_date
        )
    if key == "headless_or_ci":
        block = (profile.get("protocols", {}) or {}).get("headless_or_ci", {}) or {}
        return _cell_with_claim(
            block, render_value=_tri(block.get("value")), evaluation_date=evaluation_date
        )
    return "unknown"


def render_matrix(profiles: list[ProfileFile], *, evaluation_date: _dt.date) -> str:
    sorted_profiles = sorted(profiles, key=lambda p: p.agent_id)

    lines: list[str] = []
    lines.append("# Agent Matrix")
    lines.append("")
    lines.append(GENERATED_NOTICE.rstrip("\n"))
    lines.append(
        "Comparison of profiled AI coding agents. Every factual cell traces to a "
        "source record in the agent's profile and is labeled with its claim status. "
        "This matrix is a decision aid, not a ranking \u2014 there is no overall score."
    )
    lines.append("")

    header_cells = [display for _, display in COLUMNS]
    lines.append("| " + " | ".join(header_cells) + " |")
    lines.append("|" + "|".join(["---"] * len(COLUMNS)) + "|")

    for p in sorted_profiles:
        cells = [_cell_for(p.data, key, evaluation_date=evaluation_date) for key, _ in COLUMNS]
        cells = [c.replace("|", "/").replace("\n", " ") for c in cells]
        lines.append("| " + " | ".join(cells) + " |")

    lines.append("")
    lines.append(LEGEND.rstrip("\n"))
    lines.append("")

    lines.append(
        f"_{len(sorted_profiles)} profile(s) included. Phase 1 of Kernux: the matrix "
        "grows as profiles are added and verified._"
    )
    lines.append("")
    return "\n".join(lines)


def generate(*, evaluation_date: _dt.date, profiles: list[ProfileFile] | None = None) -> str:
    if profiles is None:
        profiles = profile_io.discover_profiles()
    errors = validate_profiles.validate_all(evaluation_date=evaluation_date, profiles=profiles)
    if errors:
        raise ValueError(
            f"refusing to generate matrix: {len(errors)} validation error(s); "
            f"first: {errors[0].render()}"
        )
    return render_matrix(profiles, evaluation_date=evaluation_date)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="tools.generate_matrix",
        description="Generate the deterministic Kernux agent matrix.",
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--evaluation-date",
        type=str,
        default=None,
        help="ISO date used for staleness computation (default: today).",
    )
    args = parser.parse_args(argv)

    evaluation_date = (
        profile_io.parse_iso_date(args.evaluation_date)
        if args.evaluation_date
        else _dt.date.today()
    )

    try:
        rendered = generate(evaluation_date=evaluation_date)
    except ValueError as exc:
        print(f"generate_matrix: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if not MATRIX_PATH.is_file():
            print(
                f"generate_matrix --check: {MATRIX_PATH.name} does not exist; "
                "run without --check to create it.",
                file=sys.stderr,
            )
            return 1
        committed = MATRIX_PATH.read_text(encoding="utf-8")
        if committed != rendered:
            print(
                "generate_matrix --check: committed matrix differs from regenerated output.",
                file=sys.stderr,
            )
            print(
                "Run `uv run python -m tools.generate_matrix` to update, then commit.",
                file=sys.stderr,
            )
            return 1
        print(f"OK   {MATRIX_PATH.name} is up to date.")
        return 0

    MATRIX_PATH.parent.mkdir(parents=True, exist_ok=True)
    MATRIX_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {MATRIX_PATH.name} ({len(rendered)} bytes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
